name: Auto Generate Blog Post

on:
  schedule:
    - cron: '0 9 * * 1'
    - cron: '0 9 * * 4'
  workflow_dispatch:

jobs:
  generate-blog:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate blog post
        run: node scripts/generateBlogPost.js

      - name: Generate RSS feed
        run: node scripts/generateRSS.js

      - name: Commit and push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/blog/*.md public/rss.xml
          git commit -m "Auto-generate blog post [skip ci]" || echo "No changes"
          git push